import java.text.SimpleDateFormat

plugins {
    id('com.android.application')
    id('org.jetbrains.kotlin.android')
}

android {
    namespace 'com.pengxh.daily.app'
    compileSdk 36

    lint {
        disable 'NewerVersionAvailable'
        disable 'GradleDependency'
    }

    defaultConfig {
        applicationId 'com.pengxh.daily.app'
        minSdk 26
        targetSdk 36
        versionCode 2423
        versionName '2.4.2.3'
    }

    flavorDimensions += 'versionCode'

    signingConfigs {
        release {
            storeFile file('DailyTask.jks')
            storePassword '123456789'
            keyAlias 'key0'
            keyPassword '123456789'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

//    GString id = "com.alibaba.android.${randomCode()}"
//    productFlavors {
//        daily {
//            applicationId = id
//        }
//    }

    packagingOptions {
        exclude 'META-INF/NOTICE.md'
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/versions/9/OSGI-INF/MANIFEST.MF'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    applicationVariants.configureEach {
        outputs.configureEach {
            outputFileName = "DT_${getBuildDate()}_${android.defaultConfig.versionName}.apk"
        }
    }
}

static def randomCode() {
    String alphabetsInLowerCase = 'abcdefghijklmnopqrstuvwxyz'
    String randomString = ""
    for (i in 0..5) {
        int randomIndex = Math.random() * alphabetsInLowerCase.length()
        randomString += alphabetsInLowerCase[randomIndex]
    }
    return randomString
}

static def getBuildDate() {
    SimpleDateFormat dateFormat = new SimpleDateFormat('yyyyMMdd', Locale.CHINA)
    return dateFormat.format(System.currentTimeMillis())
}

dependencies {
    implementation project(':lite')
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    //数据库框架
    implementation 'androidx.room:room-runtime:2.8.2'
    annotationProcessor 'androidx.room:room-compiler:2.8.2'
    //邮件
    implementation 'com.sun.mail:android-mail:1.6.8'
    implementation 'com.sun.mail:android-activation:1.6.8'
    //日期、时间选择器
    implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:4.1.15'
    implementation 'com.google.code.gson:gson:2.14.0'
    //返回值转换器
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    //okhttp3日志拦截器
    implementation 'com.squareup.okhttp3:logging-interceptor:5.4.0'
    //网络请求和接口封装
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.okhttp3:okhttp:5.4.0'
}
